apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jvcjunior/client 
      context: front
      docker:
        dockerfile: dockerfile 
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: jvcjunior/comments 
      context: comments
      docker:
        dockerfile: dockerfile 
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jvcjunior/event-bus 
      context: event-bus
      docker:
        dockerfile: dockerfile 
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jvcjunior/moderation 
      context: moderation
      docker:
        dockerfile: dockerfile 
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jvcjunior/posts 
      context: posts
      docker:
        dockerfile: dockerfile 
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: jvcjunior/query 
      context: query
      docker:
        dockerfile: dockerfile 
      sync:
        manual:
          - src: '*.js'
            dest: .